import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";

const spiegel = localFont({
  src: [
    {
      path: "../fonts/Spiegel-Sans-Font/WOFF2/SpiegelSans-5Regular_TRIAL.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../fonts/Spiegel-Sans-Font/WOFF2/SpiegelSans-6SemiBold_TRIAL.woff2",
      weight: "600",
      style: "semibold",
    },
    {
      path: "../fonts/Spiegel-Sans-Font/WOFF2/SpiegelSans-7Bold_TRIAL.woff2",
      weight: "700",
      style: "bold",
    },
    {
      path: "../fonts/Spiegel-Sans-Font/WOFF2/SpiegelSans-8ExtraBold_TRIAL.woff2",
      weight: "800",
      style: "extrabold",
    },
  ],
});
export const metadata: Metadata = {
  title: "LOL challenge",
  description: "Generated by create next app",
  icons: {
    icon: "./favicon.ico",
    href: "./favicon.ico",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={spiegel.className}>{children}</body>
    </html>
  );
}
