import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "LOL challenge",
  description: "Generated by create next app",
  icons: {
    icon: "./favicon.ico",
    href: "./favicon.ico",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
